# Generated by Django 4.2.6 on 2023-10-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, null=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "parent_error",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="errors.errortype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrorSummery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_entry", models.DateTimeField()),
                ("last_entry", models.DateTimeField()),
                ("amount", models.IntegerField(default=0)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries_summery",
                        to="errors.errortype",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_entry"],
            },
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("body", models.TextField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="errors.errortype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ErrorDateAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "error",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="errors.errortype",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "error")},
            },
        ),
    ]
