# Generated by Django 4.2.6 on 2023-10-21 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="error",
            name="eid",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="error",
            name="filtered",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="errortype",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
