# Generated by Django 4.2.6 on 2023-10-21 12:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errors", "0003_remove_errorsummery_type_delete_errordateamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="error",
            name="params",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
