# Generated by Django 4.2.6 on 2023-10-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errors", "0004_error_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="errortype",
            name="error_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="errortype",
            name="notification_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
