# Generated by Django 4.2.6 on 2023-10-21 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errors", "0005_errortype_error_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errortype",
            name="solutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
