# Generated by Django 4.2.6 on 2023-10-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="provider",
            field=models.CharField(
                choices=[
                    ("error_handler.notifications.providers.site", "site"),
                    ("error_handler.notifications.providers.email", "email"),
                    ("error_handler.notifications.providers.telegram", "telegram"),
                ]
            ),
        ),
    ]
