# Generated by Django 4.2.6 on 2023-10-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("errors", "0003_remove_errorsummery_type_delete_errordateamount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorSummery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_entry", models.DateTimeField()),
                ("last_entry", models.DateTimeField()),
                ("amount", models.IntegerField(default=0)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries_summery",
                        to="errors.errortype",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_entry"],
            },
        ),
        migrations.CreateModel(
            name="ErrorDateAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.IntegerField(default=0)),
                (
                    "error",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="errors.errortype",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "error")},
            },
        ),
    ]
