# Generated by Django 4.2.6 on 2023-10-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_errorsummery_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorsummery",
            name="last_error_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
